import type { CaseItem, LogoItem, Metric } from "./types";

export const CLIENTS = {
  hero: {
    eyebrow: "Clients",
    title: "Partners in performance.",
    sub: "Fortunate to have scaled alongside some of the boldest names in their categories.",
    primaryCta: { label: "Work with us", href: "/get-in-touch" },
    secondaryCta: { label: "See our work", href: "#cases" },
  },
  // v4.0: one clean wall of clients + a small startups row (Hypolator moved to startups).
  // Group headings removed. Logo assets deferred -> names render as labelled placeholders.
  logoWall: {
    eyebrow: "Our clients",
    title: "The companies we build with",
    lead: "From market leaders to emerging disruptors, we partner with organisations that shape industries and scale with intent.",
    logos: [
      { name: "Hamar Hajaala" },
      { name: "Dainikpuri" },
      { name: "Narayana" },
      { name: "The Cake Room" },
      { name: "Sparsh" },
      { name: "Sree Vidyanikethan" },
      { name: "New York" },
      { name: "Nav Bharath" },
      { name: "Mohan Babu University" },
      { name: "Maison AVA" },
      { name: "Kutchina" },
      { name: "Kespariya" },
      { name: "AVA" },
      { name: "24 Frames" },
      { name: "Valmar" },
      { name: "EY" },
      { name: "Korn Ferry" },
      { name: "S&P" },
    ] satisfies LogoItem[],
    startups: [
      { name: "Hypolator" },
      { name: "RunTailor" },
      { name: "Kalaclap" },
      { name: "Papa Pawsome" },
      { name: "Therapeutics" },
      { name: "SpaceBasic" },
    ] satisfies LogoItem[],
  },
  // Interim text (logos deferred). Carried in, not specified in the brief -> flagged.
  keyClients: {
    eyebrow: "Across industries",
    title: "Key clients handled across industries",
    lead: "Brands the team has worked with across categories. Logos to follow.",
    groups: [
      { label: "Retail & fashion", names: ["Gap", "A&F", "Walmart", "Macy's", "Tommy Hilfiger", "Levi's"] },
      { label: "Media & entertainment", names: ["Sony", "Star", "Colors", "&tv", "Eros International"] },
      { label: "FMCG", names: ["HUL", "P&G", "Dabur", "ITC", "Patanjali", "RHPL"] },
      { label: "Financial services", names: ["Birla Sun Life", "ICICI Pru", "MobiKwik", "Paytm"] },
      { label: "Automotive", names: ["Maruti", "Honda", "Hyundai", "KIA"] },
      { label: "Education", names: ["VIT", "SRM", "Aakash", "FIITJEE", "Narayana", "Sri Chaitanya"] },
      {
        label: "Digital & retail",
        names: ["Amazon", "Flipkart", "Snapdeal", "Big Bazaar", "Modern Retail", "Disney", "GVK"],
      },
    ],
  },
  stats: [
    { to: 127, suffix: "+", label: "Clients served" },
    { to: 21, label: "Sectors" },
    { to: 53, suffix: "+", label: "Institutional" },
    { to: 14, suffix: "+", label: "Countries" },
  ] satisfies Metric[],
  cases: {
    eyebrow: "Impact highlights",
    title: "Complex challenges, clarified and delivered",
    lead: "A few of the rooms we stayed in until the number moved.",
    items: [
      {
        slug: "sakshi-media-group",
        name: "Sakshi Media Group",
        logo: "sakshi.jpg",
        eyebrow: "Multi-vertical turnaround",
        stat: { prefix: "₹", value: "147", suffix: "cr" },
        statLabel: "Profit, up from a ₹14 cr loss",
        body: "TV rank 2nd to 3rd, 100%+ YoY digital growth. Standalone P&Ls, Must-Win Battles, and India's first paperless newsroom.",
      },
      {
        slug: "dainik-bhaskar",
        name: "Dainik Bhaskar",
        logo: "dainik-Bhaskar.jpg",
        eyebrow: "National media",
        stat: { value: "4th" },
        statLabel: "Among the world's largest by circulation",
        body: "Consumer-connect programmes, insights-led GTM, and cross-functional alignment at national scale.",
      },
      {
        slug: "mohan-babu-university",
        name: "Mohan Babu University",
        logo: "MBU.jpg",
        eyebrow: "Brownfield to university",
        stat: { value: "18k", suffix: "+" },
        statLabel: "Students, up from 7,000",
        body: "86% placements, 3,100 offers, NAAC A+. Partnerships with Penn State, RWTH, and UW-Madison.",
      },
      {
        slug: "valmar",
        name: "Valmar",
        logo: "valmar.jpg",
        eyebrow: "Student housing & food-tech",
        stat: { prefix: "₹", value: "80", suffix: "cr+" },
        statLabel: "FY25 revenue",
        body: "5,000+ beds, 24,000 meals a day, ₹38 cr+ EBITDA, with a 10,000+ bed pipeline.",
      },
    ] satisfies CaseItem[],
  },
  cta: {
    primaryCta: { label: "Book a working session", href: "/get-in-touch" },
  },
};
